export const SET_ERROR = 'product/SET_ERROR'
export const SET_PRODUCT_LIST = 'product/SET_PRODUCT_LIST'
export const SET_TYPE_LIST = 'product/SET_TYPE_LIST'
export const SET_CATEGORY_LIST = 'product/SET_CATEGORY_LIST'
export const SET_PROVIDER_LIST = 'product/SET_PROVIDER_LIST'
export const SET_RENT_TYPE_LIST = 'product/SET_RENT_TYPE_LIST'
export const SET_PRODUCT = 'product/SET_PRODUCT'
