export const SET_ERROR = 'customer/SET_ERROR'
export const SET_CUSTOMER_LIST = 'customer/SET_CUSTOMER_LIST'
export const SET_ID_TYPE_LIST = 'customer/SET_ID_TYPE_LIST'
export const SET_RENT_TYPE_LIST = 'customer/SET_RENT_TYPE_LIST'
export const SET_PRICE_TYPE_LIST = 'customer/SET_PRICE_TYPE_LIST'
export const SET_EXONERATION_TYPE_LIST = 'customer/SET_EXONERATION_TYPE_LIST'
export const SET_CUSTOMER = 'customer/SET_CUSTOMER'
