INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(1, 'Proformas en general');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(2, 'Proformas anuladas');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(3, 'Apartados en general');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(4, 'Apartados anulados');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(5, 'Ordenes de servicio en general');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(6, 'Ordenes de servicio anuladas');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(7, 'Ventas en general');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(8, 'Ventas anuladas');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(9, 'Ventas por vendedor');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(10, 'Resumen de ventas por línea');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(11, 'Detalle de ventas por línea');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(12, 'Devoluciones de clientes');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(13, 'Devoluciones de clientes anuladas');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(14, 'Reporte de costos de inventario');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(20, 'Compras en general');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(21, 'Compras anuladas');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(30, 'Cuentas por cobrar a clientes');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(31, 'Cuentas por cobrar canceladas');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(32, 'Cuentas por pagar a proveedores');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(33, 'Cuentas por pagar canceladas');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(34, 'Pagos a cuentas por cobrar de clientes');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(35, 'Pagos a cuentas por pagar de proveedores');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(40, 'Conciliación bancaria');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(41, 'Resumen de movimientos');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(42, 'Detalle de egresos');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(43, 'Detalle de ingresos');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(50, 'Documentos electrónicos emitidos');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(51, 'Documentos electrónicos recibidos');
INSERT INTO catalogoreporte (IdReporte, NombreReporte) VALUES(52, 'Resumen de comprobantes electrónicos');