INSERT INTO Provincia VALUES(1,'SAN JOSE');
INSERT INTO Provincia VALUES(2,'ALAJUELA');
INSERT INTO Provincia VALUES(3,'CARTAGO');
INSERT INTO Provincia VALUES(4,'HEREDIA');
INSERT INTO Provincia VALUES(5,'GUANACASTE');
INSERT INTO Provincia VALUES(6,'PUNTARENAS');
INSERT INTO Provincia VALUES(7,'LIMON');
