use puntoventa;
INSERT INTO TipoIdentificacion VALUES(0, 'Cédula Física');
INSERT INTO TipoIdentificacion VALUES(1, 'Cédula Jurídica');
INSERT INTO TipoIdentificacion VALUES(2, 'DIMEX');
INSERT INTO TipoIdentificacion VALUES(3, 'NITE');
INSERT INTO TipoMoneda VALUES(1, 'Colones', 1, 1);
INSERT INTO TipoMoneda VALUES(2, 'Dólares', 495, 505);
INSERT INTO TipoCuentaContable VALUES(1,'D','Deudor');
INSERT INTO TipoCuentaContable VALUES(2,'C','Acreedor');
INSERT INTO ClaseCuentaContable VALUES(1,'Activo');
INSERT INTO ClaseCuentaContable VALUES(2,'Pasivo');
INSERT INTO ClaseCuentaContable VALUES(3,'Resultados');
INSERT INTO ClaseCuentaContable VALUES(4,'Patrimonio');
INSERT INTO TipoParametroContable VALUES(1, 'Ingresos Ventas', 0);
INSERT INTO TipoParametroContable VALUES(2, 'Costos de Ventas', 0);
INSERT INTO TipoParametroContable VALUES(3, 'IVA Por Pagar', 0);
INSERT INTO TipoParametroContable VALUES(4, 'Líneas de Producto', 1);
INSERT INTO TipoParametroContable VALUES(5, 'Líneas de Servicios', 1);
INSERT INTO TipoParametroContable VALUES(6, 'Cuentas de Bancos', 1);
INSERT INTO TipoParametroContable VALUES(7, 'Efectivo', 0);
INSERT INTO TipoParametroContable VALUES(8, 'Otras Condiciones de venta', 0);
INSERT INTO TipoParametroContable VALUES(9, 'Cuentas por Cobrar Clientes', 0);
INSERT INTO TipoParametroContable VALUES(10, 'Cuentas por Cobrar Tarjeta', 0);
INSERT INTO TipoParametroContable VALUES(11, 'Gastos/Comisión Tarjeta', 0);
INSERT INTO TipoParametroContable VALUES(12, 'Cuentas por Pagar Proveedores', 0);
INSERT INTO TipoParametroContable VALUES(13, 'Cuentas por Cobrar Proveedores', 0);
INSERT INTO TipoParametroContable VALUES(14, 'Cuentas de Ingresos', 1);
INSERT INTO TipoParametroContable VALUES(15, 'Cuentas de Egresos', 1);
INSERT INTO TipoParametroContable VALUES(16, 'Traslados', 1);
INSERT INTO TipoParametroContable VALUES(17, 'Cuenta de Perdidas/Ganancias', 0);
INSERT INTO TipoParametroContable VALUES(18, 'Cuenta por Pagar Particulares', 0);
INSERT INTO TipoProducto VALUES(1,'Producto');
INSERT INTO TipoProducto VALUES(2,'Servicio');
INSERT INTO TipoUnidad VALUES(1,'UND');
INSERT INTO TipoUnidad VALUES(2,'SP');
INSERT INTO CondicionVenta VALUES(1, 'Contado');
INSERT INTO CondicionVenta VALUES(2, 'Crédito');
INSERT INTO CondicionVenta VALUES(3, 'Consignación');
INSERT INTO CondicionVenta VALUES(4, 'Apartado');
INSERT INTO CondicionVenta VALUES(5, 'Arrendamiento con opción de compra');
INSERT INTO CondicionVenta VALUES(6, 'Arrendamiento en función financiera');
INSERT INTO CondicionVenta VALUES(99, 'Otros');
INSERT INTO FormaPago VALUES(1, 'Efectivo');
INSERT INTO FormaPago VALUES(2, 'Tarjeta');
INSERT INTO FormaPago VALUES(3, 'Cheque');
INSERT INTO FormaPago VALUES(4, 'Transferencia - Dep. Bancario');
INSERT INTO FormaPago VALUES(5, 'Racaudado por terceros');
INSERT INTO FormaPago VALUES(99, 'Otros');
INSERT INTO TipoMovimientoBanco VALUES(1,'D','Cheque Saliente');
INSERT INTO TipoMovimientoBanco VALUES(2,'C','Depósito Entrante');
INSERT INTO TipoMovimientoBanco VALUES(3,'C','Inversión');
INSERT INTO TipoMovimientoBanco VALUES(4,'D','Nota Débito');
INSERT INTO TipoMovimientoBanco VALUES(5,'C','Nota Crédito');
INSERT INTO TipoMovimientoBanco VALUES(6,'C','Cheque Entrante');
INSERT INTO TipoMovimientoBanco VALUES(7,'D','Depósito Saliente');
INSERT INTO Modulo VALUES(1,'Modulo archivo','mnuArchivo');
INSERT INTO Modulo VALUES(2,'Modulo parametros','MnuParam');
INSERT INTO Modulo VALUES(3,'Modulo mantenimiento','MnuMant');
INSERT INTO Modulo VALUES(4,'Modulo capturas','MnuCaptura');
INSERT INTO Modulo VALUES(5,'Modulo CXC y CXP','MnuCC');
INSERT INTO Modulo VALUES(6,'Modulo bancos','MnuBC');
INSERT INTO Modulo VALUES(7,'Modulo contabilidad','mnuConta');
INSERT INTO CatalogoReporte VALUES(1, 'Ventas en general');
INSERT INTO CatalogoReporte VALUES(2, 'Ventas anuladas');
INSERT INTO CatalogoReporte VALUES(3, 'Ventas por vendedor');
INSERT INTO CatalogoReporte VALUES(4, 'Compras en general');
INSERT INTO CatalogoReporte VALUES(5, 'Compras anuladas');
INSERT INTO CatalogoReporte VALUES(6, 'Cuentas por cobrar a clientes');
INSERT INTO CatalogoReporte VALUES(7, 'Cuentas por pagar a proveedores');
INSERT INTO CatalogoReporte VALUES(8, 'Pagos a cuentas por cobrar de clientes');
INSERT INTO CatalogoReporte VALUES(9, 'Pagos a cuentas por pagar de proveedores');
INSERT INTO CatalogoReporte VALUES(10, 'Conciliación bancaria');
INSERT INTO CatalogoReporte VALUES(11, 'Resumen de movimientos');
INSERT INTO CatalogoReporte VALUES(12, 'Detalle de egresos');
INSERT INTO CatalogoReporte VALUES(13, 'Detalle de ingresos');
INSERT INTO CatalogoReporte VALUES(14, 'Reporte resumido de ventas por línea');
INSERT INTO CatalogoReporte VALUES(15, 'Reporte detallado de ventas por línea');