USE PUNTOVENTA;
INSERT INTO Role values(3,'Parametrización Contable de Servicios','MnuParam','MnuParamPC','Permite parametrizar los servicios con las cuentas contables respectivas');
INSERT INTO Role values(51,'Mantenimiento de Particulares','MnuMant','MnuMantPArticular','Permite acceder al módulo de Mantenimiento de Particulares');
INSERT INTO Role values(56,'Mantenimiento de Sucursales','MnuMant','MnuMantSucursal','Permite acceder al módulo de Mantenimiento de Sucursales');
INSERT INTO Role values(58,'Mantenimiento de Cuentas de Ingreso','MnuMant','MnuMantCI','Permite acceder al módulo de Mantenimiento de Cuenta de Ingresos');
INSERT INTO Role values(60,'Mantenimiento del Catalogo Contable','MnuMant','MnuMantCC','Permite actualizar los datos de las cuentas del catálogo contable');
INSERT INTO Role values(100,'Módulo de Inventario','MnuMant','MnuMantInv','Permite acceder al módulo de Mantenimiento de Inventario');
INSERT INTO Role values(102,'Módulo de Ordenes de Servicio','MnuCaptura','MnuCapturaOrdenServicio','Permite registrar las Ordenes de Servicio');
INSERT INTO Role values(103,'Módulo de Compras','MnuCaptura','MnuCapturaCompra','Permite registrar las Compras');
INSERT INTO Role values(104,'Módulo de Proformas','MnuCaptura','MnuCapturaProforma','Permite registrar las Proformas');
INSERT INTO Role values(105,'Módulo de Ordenes de Compra','MnuCaptura','MnuCapturaOrden','Permite registrar las ordenes de compra');
INSERT INTO Role values(106,'Módulo de Devoluciones a Provedores','MnuCaptura','MnuDevolucionProveedor','Permite registrar los movimientos de devoluciones de producto a proveedores');
INSERT INTO Role values(107,'Módulo de Devoluciones de Clientes','MnuCaptura','MnuDevolucionCliente','Permite registrar los movimientos de devoluciones de producto de clientes');
INSERT INTO Role values(108,'Módulo de Traslados','MnuCaptura','MnuCapturaTraslado','Permite registrar los movimientos de Traslados de Producto');
INSERT INTO Role values(110,'Módulo de Registro de Ingresos','MnuCaptura','MnuCapturaIngreso','Permite registrar los movimientos de Ingresos');
INSERT INTO Role values(111,'Módulo de Ajustes al Inventario','MnuCaptura','MnuCapturaAI','Permite registrar los ajustes de inventario');
INSERT INTO Role values(112,'Módulo de CxP Particulares','MnuCaptura','MnuCapturaCxPP','Permite registrar las cuentas por pagar a particulares');
INSERT INTO Role values(150,'Aplicación de Créditos a Cuentas por Cobrar','MnuCC','MnuApRCxC','Permite aplicar un abono a Cuentas por Cobrar');
INSERT INTO Role values(151,'Aplicación de Créditos a Cuentas por Pagar','MnuCC','MnuApRCxP','Permite aplicar un abono a Cuentas por Pagar');
INSERT INTO Role values(152,'Aplicación de Créditos CxP Particulares','MnuCC','MnuApRCxPP','Permite aplicar un abono a Cuentas por Pagar de un particular');
INSERT INTO Role values(200,'Anulación de Créditos de Cuentas por Cobrar','MnuCC','MnuAnRCxC','Permite anular un abono a Cuentas por Cobrar');
INSERT INTO Role values(201,'Anulación de Créditos de Cuentas por Pagar','MnuCC','MnuAnRCxP','Permite anular un abono a Cuentas por Pagar');
INSERT INTO Role values(202,'Anulación de Créditos de CxP Particulares','MnuCC','MnuAnRCxPP','Permite anular un abono a Cuentas por Pagar de un particular');
INSERT INTO Role values(250,'Reimpresión de recibos de Cuentas por Cobrar','MnuCC','MnuImpCxC','Permite reimprimir recibos de cuentas por cobrar');
INSERT INTO Role values(251,'Reimpresión de recibos de Cuentas por Pagar','MnuCC','MnuImpCxP','Permite reimprimir recibos de cuentas por Pagar');
INSERT INTO Role values(252,'Reimpresión de recibos de CxP Particulares','MnuCC','MnuImpCxPP','Permite reimprimir recibos de cuentas por Pagar de un particular');
INSERT INTO Role values(300,'Módulo de movimientos en Cuentas Bancarias','MnuBC','MnuBCMov','Permite registrar y actualizar movimientos sobre cuentas');
INSERT INTO Role values(350,'Módulo de Asientos Contables','mnuConta','mnuContaAsiento','Permite registrar y actualizar asientos contables de la empresa');
INSERT INTO Role values(351,'Módulo de Cierre Contable','mnuConta','mnuContaCierre','Permite realizar el cierre mensual contable');
INSERT INTO Role values(352,'Módulo de Reportes Contables','mnuConta','mnuContaReporte','Permite acceder al menu de reportes contable');
INSERT INTO RolePorUsuario VALUES(1,1,3);
INSERT INTO RolePorUsuario VALUES(1,1,51);
INSERT INTO RolePorUsuario VALUES(1,1,56);
INSERT INTO RolePorUsuario VALUES(1,1,58);
INSERT INTO RolePorUsuario VALUES(1,1,60);
INSERT INTO RolePorUsuario VALUES(1,1,100);
INSERT INTO RolePorUsuario VALUES(1,1,102);
INSERT INTO RolePorUsuario VALUES(1,1,103);
INSERT INTO RolePorUsuario VALUES(1,1,104);
INSERT INTO RolePorUsuario VALUES(1,1,105);
INSERT INTO RolePorUsuario VALUES(1,1,106);
INSERT INTO RolePorUsuario VALUES(1,1,107);
INSERT INTO RolePorUsuario VALUES(1,1,108);
INSERT INTO RolePorUsuario VALUES(1,1,109);
INSERT INTO RolePorUsuario VALUES(1,1,110);
INSERT INTO RolePorUsuario VALUES(1,1,111);
INSERT INTO RolePorUsuario VALUES(1,1,112);
INSERT INTO RolePorUsuario VALUES(1,1,150);
INSERT INTO RolePorUsuario VALUES(1,1,151);
INSERT INTO RolePorUsuario VALUES(1,1,152);
INSERT INTO RolePorUsuario VALUES(1,1,200);
INSERT INTO RolePorUsuario VALUES(1,1,201);
INSERT INTO RolePorUsuario VALUES(1,1,202);
INSERT INTO RolePorUsuario VALUES(1,1,250);
INSERT INTO RolePorUsuario VALUES(1,1,251);
INSERT INTO RolePorUsuario VALUES(1,1,252);
INSERT INTO RolePorUsuario VALUES(1,1,300);
INSERT INTO RolePorUsuario VALUES(1,1,350);
INSERT INTO RolePorUsuario VALUES(1,1,351);
INSERT INTO RolePorUsuario VALUES(1,1,352);