use puntoventa;
INSERT INTO TipoIdentificacion VALUES(0, 'Cédula Física');
INSERT INTO TipoIdentificacion VALUES(1, 'Cédula Jurídica');
INSERT INTO TipoIdentificacion VALUES(2, 'DIMEX');
INSERT INTO TipoIdentificacion VALUES(3, 'NITE');
INSERT INTO TipoMoneda values(1, 'Colones', 1, 1);
INSERT INTO TipoMoneda values(2, 'Dólares', 495, 505);
INSERT INTO TipoCuentaContable VALUES(1,'D','Deudor');
INSERT INTO TipoCuentaContable VALUES(2,'C','Acreedor');
INSERT INTO ClaseCuentaContable VALUES(1,'Activo');
INSERT INTO ClaseCuentaContable VALUES(2,'Pasivo');
INSERT INTO ClaseCuentaContable VALUES(3,'Resultados');
INSERT INTO ClaseCuentaContable VALUES(4,'Patrimonio');
INSERT INTO TipoParametroContable VALUES(1, 'Ingresos Ventas', 0);
INSERT INTO TipoParametroContable VALUES(2, 'Costos de Ventas', 0);
INSERT INTO TipoParametroContable VALUES(3, 'IVA Por Pagar', 0);
INSERT INTO TipoParametroContable VALUES(4, 'Líneas de Producto', 1);
INSERT INTO TipoParametroContable VALUES(5, 'Líneas de Servicios', 1);
INSERT INTO TipoParametroContable VALUES(6, 'Cuentas de Bancos', 1);
INSERT INTO TipoParametroContable VALUES(7, 'Efectivo', 0);
INSERT INTO TipoParametroContable VALUES(8, 'Otras Condiciones de venta', 0);
INSERT INTO TipoParametroContable VALUES(9, 'Cuentas por Cobrar Clientes', 0);
INSERT INTO TipoParametroContable VALUES(10, 'Cuentas por Cobrar Tarjeta', 0);
INSERT INTO TipoParametroContable VALUES(11, 'Gastos/Comisión Tarjeta', 0);
INSERT INTO TipoParametroContable VALUES(12, 'Cuentas por Pagar Proveedores', 0);
INSERT INTO TipoParametroContable VALUES(13, 'Cuentas por Cobrar Proveedores', 0);
INSERT INTO TipoParametroContable VALUES(14, 'Cuentas de Ingresos', 1);
INSERT INTO TipoParametroContable VALUES(15, 'Cuentas de Egresos', 1);
INSERT INTO TipoParametroContable VALUES(16, 'Traslados', 1);
INSERT INTO TipoParametroContable VALUES(17, 'Cuenta de Perdidas/Ganancias', 0);
INSERT INTO TipoParametroContable VALUES(18, 'Cuenta por Pagar Particulares', 0);
INSERT INTO TipoProducto values(1,'Producto');
INSERT INTO TipoProducto values(2,'Servicio');
INSERT INTO TipoUnidad values(1,'UND');
INSERT INTO TipoUnidad values(2,'SP');
INSERT INTO CondicionVenta values(1, 'Contado');
INSERT INTO CondicionVenta values(2, 'Crédito');
INSERT INTO CondicionVenta values(3, 'Consignación');
INSERT INTO CondicionVenta values(4, 'Apartado');
INSERT INTO CondicionVenta values(5, 'Arrendamiento con opción de compra');
INSERT INTO CondicionVenta values(6, 'Arrendamiento en función financiera');
INSERT INTO CondicionVenta values(99, 'Otros');
INSERT INTO FormaPago values(1, 'Efectivo');
INSERT INTO FormaPago values(2, 'Tarjeta');
INSERT INTO FormaPago values(3, 'Cheque');
INSERT INTO FormaPago values(4, 'Transferencia - Dep. Bancario');
INSERT INTO FormaPago values(5, 'Racaudado por terceros');
INSERT INTO FormaPago values(99, 'Otros');
INSERT INTO TipoMovimientoBanco values(1,'D','Cheque Saliente');
INSERT INTO TipoMovimientoBanco values(2,'C','Depósito Entrante');
INSERT INTO TipoMovimientoBanco values(3,'C','Inversión');
INSERT INTO TipoMovimientoBanco values(4,'D','Nota Débito');
INSERT INTO TipoMovimientoBanco values(5,'C','Nota Crédito');
INSERT INTO TipoMovimientoBanco values(6,'C','Cheque Entrante');
INSERT INTO TipoMovimientoBanco values(7,'D','Depósito Saliente');