INSERT INTO role (IdRole, Nombre, MenuPadre, MenuItem, Descripcion) VALUES
(1, 'ADMINISTRADOR', '', '', 'Concede permisos de administrador'),
(2, 'CONTADOR', '', '', 'Concede permisos para visualizar reportes'),
(48, 'Selecciona sucursal para consulta', '', '', 'Permite seleccionar la sucursal para la consulta de movimientos'),
(49, 'Anulación de registros', '', '', 'Permite anular transacciones en general'),
(50, 'Modifica descripción del producto', '', '', 'Permite modificar la descripción del producto por facturar'),
(51, 'Modifica condición de crédito del cliente', '', '', 'Permite modificar la condición de crédito de un cliente'),
(52, 'Modifica precio de venta', '', '', 'Permite modificar el precio de venta del producto'),
(53, 'Cierre Diario', 'mnuArchivo', 'mnuArchivoCierre', 'Permite ejecutar el cierre diario'),
(54, 'Consulta Cierre Diario', 'mnuArchivo', 'MnuArchivoConsultaCierre', 'Permite consultar el histórico del cierre diario'),
(55, 'Módulo de Registro de Ingresos', 'mnuArchivo', 'MnuArchivoIngreso', 'Permite registrar los movimientos de ingresos'),
(56, 'Módulo de Registro de Egresos', 'mnuArchivo', 'MnuArchivoEgreso', 'Permite registrar los movimientos de egresos'),
(57, 'Menu de Reportes', 'mnuArchivo', 'MnuArchivoReporte', 'Permite acceder el menu de reportes'),
(58, 'Parametrización Contable de Servicios', 'MnuParam', 'MnuParamPC', 'Permite parametrizar los servicios con las cuentas contables respectivas'),
(59, 'Parametrización de Bancos Adquirientes', 'MnuParam', 'MnuParamBA', 'Permite parametrizar los bancos adquirientes'),
(60, 'Parametrización de Cuentas Bancarias', 'MnuParam', 'MnuParamCB', 'Permite parametrizar las cuentas bancarias'),
(61, 'Parametrización de Empresa', 'MnuParam', 'MnuParamEmpresa', 'Permite parametrizar la información de la empresa'),
(100, 'Mantenimiento de Clientes', 'MnuMant', 'MnuMantCliente', 'Permite acceder al catalogo de clientes'),
(101, 'Mantenimiento de Líneas', 'MnuMant', 'MnuMantLinea', 'Permite acceder al catalogo de líneas'),
(102, 'Mantenimiento de Proveedores', 'MnuMant', 'MnuMantProveedor', 'Permite acceder al catalogo de proveedores'),
(103, 'Mantenimiento de Productos', 'MnuMant', 'MnuMantProducto', 'Permite acceder al catalogo de productos'),
(104, 'Mantenimiento de Usuarios', 'MnuMant', 'MnuMantUsuario', 'Permite crear y parametrizar usuarios del sistema'),
(105, 'Mantenimiento de Cuentas de Ingreso', 'MnuMant', 'MnuMantCI', 'Permite acceder al catalogo de cuenta de ingresos'),
(106, 'Mantenimiento de Cuentas de Egreso', 'MnuMant', 'MnuMantCE', 'Permite acceder al catalogo de cuenta de egresos'),
(107, 'Mantenimiento de Vendedores', 'MnuMant', 'MnuMantVend', 'Permite acceder al catalogo de vendedores de la empresa'),
(108, 'Mantenimiento del Catalogo Contable', 'MnuMant', 'MnuMantCC', 'Permite actualizar los datos de las cuentas del catálogo contable'),
(109, 'Mantenimiento del Inventario', 'MnuMant', 'MnuMantInv', 'Permite acceder al módulo del inventario'),
(200, 'Módulo de Proformas', 'MnuCaptura', 'MnuCapturaProforma', 'Permite registrar las proformas'),
(201, 'Módulo de Ordenes de Servicio', 'MnuCaptura', 'MnuCapturaOrdenServicio', 'Permite registrar las ordenes de servicio'),
(202, 'Módulo de Apartados', 'MnuCaptura', 'MnuCapturaApartado', 'Permite registrar los registros de apartados'),
(203, 'Módulo de Facturación', 'MnuCaptura', 'MnuCapturaFactura', 'Permite registrar la Facturación'),
(204, 'Módulo de Devoluciones de Clientes', 'MnuCaptura', 'MnuDevolucionCliente', 'Registra movimientos de devoluciones de producto de clientes'),
(250, 'Módulo de Compras', 'MnuCompra', 'MnuCompraRegistro', 'Permite registrar las Compras'),
(251, 'Módulo de Ordenes de Compra', 'MnuCompra', 'MnuCompraOrden', 'Permite registrar las ordenes de compra'),
(252, 'Módulo de Devoluciones a Provedores', 'MnuCompra', 'MnuCompraDevolucion', 'Registra movimientos de devoluciones de producto a proveedores'),
(253, 'Módulo de Ingreso de Traslados', 'MnuCompra', 'MnuCompraTraslado', 'Permite registrar los traslados de mercancias'),
(254, 'Módulo de Aplicación de Traslados', 'MnuCompra', 'MnuCompraAplicTraslado', 'Permite aplicar el registro de traslado'),
(255, 'Módulo de Ajustes al Inventario', 'MnuCompra', 'MnuCompraAjusteInv', 'Permite registrar los ajustes de inventario'),
(300, 'Aplicación de Pagos a Cuentas por Cobrar', 'MnuCC', 'MnuApRCxC', 'Permite aplicar un abono a cuentas por cobrar'),
(301, 'Aplicación de Pagos a Cuentas por Pagar', 'MnuCC', 'MnuApRCxP', 'Permite aplicar un abono a cuentas por pagar'),
(302, 'Gestión de Movimientos de Cuentas por Cobrar', 'MnuCC', 'MnuAnRCxC', 'Permite imprimir o anular un abono de una Cuentas por Cobrar'),
(303, 'Gestión de Movimientos de Cuentas por Pagar', 'MnuCC', 'MnuAnRCxP', 'Permite imprimir o anular un abono de una Cuentas por Pagar'),
(304, 'Aplicación de Pagos a Apartados', 'MnuCC', 'MnuApRApartado', 'Permite aplicar un abono a un apartado'),
(305, 'Aplicación de Pagos a Ordenes de Servicio', 'MnuCC', 'MnuApROrdenServicio', 'Permite aplicar un abono a una orden de servicio'),
(306, 'Gestión de Movimientos de Apartados', 'MnuCC', 'MnuAnRApartado', 'Permite imprimir o anular un abono de un aparado'),
(307, 'Gestión de Movimientos de Ordenes de Servicio', 'MnuCC', 'MnuAnROrdenServicio', 'Permite imprimir o anular un abono de una orden de servicio'),
(350, 'Módulo de movimientos en Cuentas Bancarias', 'MnuBC', 'MnuBCMov', 'Permite registrar y actualizar movimientos sobre cuentas'),
(351, 'Módulo de Asientos Contables', 'MnuConta', 'MnuContaAsiento', 'Permite registrar y actualizar asientos contables de la empresa'),
(352, 'Módulo de Cierre Contable', 'MnuConta', 'MnuContaCierre', 'Permite realizar el cierre mensual contable'),
(353, 'Módulo de Reportes Contables', 'MnuConta', 'MnuContaReporte', 'Permite acceder al menu de reportes contable'),
(400, 'Registro de Factura de Compra', 'MnuDocElect', 'MnuDocElectFC', 'Permite registrar facturas de compra electrónicas'),
(401, 'Consulta de Documentos Electrónicos Pendientes', 'MnuDocElect', 'MnuDocElectCDE', 'Permite consultar documentos pendientes de procesar'),
(402, 'Consulta de Documentos Electrónicos Procesados', 'MnuDocElect', 'MnuDocElectRDE', 'Permite revisar documentos procesados'),
(403, 'Documentos Electrónicos', 'MnuDocElect', 'MnuDocElectADE', 'Permite registrar facturas electrónicas recibidas');