USE PUNTOVENTA;
INSERT INTO Role values(1,'Cierre Diario','mnuArchivo','mnuArchivoCierre','Permite ejecutar el cierre diario');
INSERT INTO Role values(2,'Menu de Reportes','mnuArchivo','MnuArchivoReporte','Permite acceder el menu de reportes');
INSERT INTO Role values(4,'Parametrización de Tipos de Moneda','MnuParam','MnuParamTM','Permite parametrizar los tipos de monedas para el desglose de pagos');
INSERT INTO Role values(5,'Parametrización de Bancos Adquirientes','MnuParam','MnuParamBA','Permite parametrizar los bancos adquirientes');
INSERT INTO Role values(6,'Respaldo de datos','mnuArchivo','mnuArchivoRespaldo','Permite ejecutar el respaldo en línea de la base de datos del sistema');
INSERT INTO Role values(50,'Mantenimiento de Clientes','MnuMant','MnuMantCliente','Permite acceder al módulo de Mantenimiento de Clientes');
INSERT INTO Role values(52,'Mantenimiento de Líneas','MnuMant','MnuMantLinea','Permite acceder al módulo de Mantenimiento de Líneas');
INSERT INTO Role values(53,'Mantenimiento de Proveedores','MnuMant','MnuMantProveedor','Permite acceder al módulo de Mantenimiento de Proveedores');
INSERT INTO Role values(54,'Mantenimiento de Productos','MnuMant','MnuMantProducto','Permite acceder al módulo de Mantenimiento de Productos');
INSERT INTO Role values(55,'Mantenimiento de Usuarios','MnuMant','MnuMantUsuario','Permite acceder al módulo de Mantenimiento de Usuarios');
INSERT INTO Role values(61,'Mantenimiento de Vendedores','MnuMant','MnuMantVend','Permite actualizar los datos de los vendedores de la empresa');
INSERT INTO Role values(101,'Módulo de Facturación','MnuCaptura','MnuCapturaFactura','Permite registrar la Facturación');
INSERT INTO RolePorUsuario VALUES(2,1,1);
INSERT INTO RolePorUsuario VALUES(2,1,2);
INSERT INTO RolePorUsuario VALUES(2,1,4);
INSERT INTO RolePorUsuario VALUES(2,1,5);
INSERT INTO RolePorUsuario VALUES(2,1,6);
INSERT INTO RolePorUsuario VALUES(2,1,50);
INSERT INTO RolePorUsuario VALUES(2,1,52);
INSERT INTO RolePorUsuario VALUES(2,1,53);
INSERT INTO RolePorUsuario VALUES(2,1,54);
INSERT INTO RolePorUsuario VALUES(2,1,55);
INSERT INTO RolePorUsuario VALUES(2,1,61);
INSERT INTO RolePorUsuario VALUES(2,1,101);